version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: MyStrongPassword
    volumes:
      - /opt/docker/mariadb:/var/lib/mysql
  
  ghost:
    image: ghost:alpine
    restart: always
    depends_on:
      - db
    environment:
      url: http:localhost:8080
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: MyStrongPassword
      database__connection__database: ghost
    volumes:
        - ./content:/var/lib/ghost/content
        - ./config.production.json:/var/lib/ghost/config.production.json
